m = float(input('Digite um Valor em metros:'))
d = (m *10)
c = (m * 100)
mm = (m * 1000)
dam = (m / 10)
h = (m / 100)
k = (m /1000)
print('O valor de {} em centimetros é:{}cm'.format(m , c))
print('O valor de {} em milimetros é:{}mm'.format(m , mm))
print('O valor de {} em Decímetro  é:{}dm'.format(m , d))
print('O valor de {} em Decâmetro é:{}dam'.format(m , dam))
print('O valor de {} em Hectômetro é:{}hm'.format(m , h))
print('O valor de {} em kilômetro é:{}km'.format(m , k))